### ISSUE TITLE
BUG: azResourceGraphQuery does not want management group ID

### ISSUE THREAD

**Issue by cjedro** [webdevops/helm-azure-tpl#77]
docs:

```
Executes Azure ResourceGraph query against selected subscription IDs or management group IDs (as string comma separated or string array)
```

templates/configmap.azure.tpl

```yaml
apiVersion: v1
data:
  test: |
    {{ azResourceGraphQuery "9c1de352-64a4-4509-b3fc-4ef2df8db9b8" `resourcecontainers | where type == "microsoft.resources/subscriptions"` | toYaml }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test
```

command:

helm azure-tpl apply --target.fileext=.yaml ./templates/*.tpl

error:

```
INFO    found 127 Azure Subscriptions   {"sourcePath": "templates/configmap.azure.tpl", "targetPath": "templates/configmap.azure.yaml"}
FATAL   unable to process template: 'template: templates/configmap.azure.tpl:4:7: executing "templates/configmap.azure.tpl" at <azResourceGraphQuery "9c1de352-64a4-4509-b3fc-4ef2df8db9b8" `resourcecontainers | where type == "microsoft.resources/subscriptions"`>: error calling azResourceGraphQuery: POST https://management.azure.com/providers/Microsoft.ResourceGraph/resources
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "error": {
    "code": "BadRequest",
    "message": "Please provide below info when asking for support: timestamp = 2025-03-21T14:25:44.1694624Z, correlationId = 481548e4-b524-4145-b1e8-89b84c37b9b4.",
    "details": [
      {
        "code": "NoValidSubscriptionsInQueryRequest",
        "message": "There must be at least one subscription that is eligible to contain resources. Given: '9c1de352-64a4-4509-b3fc-4ef2df8db9b8'."
      }
    ]
  }
}
--------------------------------------------------------------------------------
'       {"sourcePath": "templates/configmap.azure.tpl", "targetPath": "templates/configmap.azure.yaml"}
Error: plugin "azure-tpl" exited with error
```

**Comment by cjedro** [comment]
nevermind, looking into the go code i´ve found the solution.. 

```yaml
apiVersion: v1
data:
  test: |
    {{ azResourceGraphQuery "/providers/microsoft.management/managementgroups/9c1de352-64a4-4509-b3fc-4ef2df8db9b8" `resourcecontainers | where type == "microsoft.resources/subscriptions"` | toYaml }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: test
```
